server:
  port: 8085

spring:
  application:
    name: CONFIGSERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ganeshcoder4043/micro-configserver-tutorial.git
          clone-on-start: true